use chrono::Utc;
use postpub_types::{GenerateArticleRequest, GenerationOutput, PostpubConfig, SearchResult};

use crate::{
    aiforge::AiforgeEngine,
    articles::{markdown_to_html, preview_html, ArticleStore},
    error::Result,
    templates::TemplateStore,
    AppContext,
};

#[derive(Debug, Clone)]
pub struct GenerationService {
    context: AppContext,
}

impl GenerationService {
    pub fn new(context: AppContext) -> Self {
        Self { context }
    }

    pub async fn generate(&self, request: GenerateArticleRequest) -> Result<GenerationOutput> {
        let bundle = self.context.config_store().load_bundle()?;
        let config = bundle.config.clone();

        let engine = AiforgeEngine::new(self.context.http_client().clone(), bundle.aiforge_config);
        let (mode, sources) = engine
            .collect_sources(
                &request.topic,
                &request.reference_urls,
                config.aiforge_search_min_results,
                config.aiforge_search_max_results,
            )
            .await?;

        let title = build_title(&request);
        let markdown = compose_markdown(&title, &request, &config, &mode, &sources);
        let format = normalize_format(&config.article_format);
        let preview = render_preview_html(
            &format,
            &markdown,
            &title,
            &mode,
            &sources,
            &request,
            &TemplateStore::new(self.context.paths().clone()),
            &config,
        )?;
        let output_content = match format.as_str() {
            "html" => preview.clone(),
            "md" => markdown.clone(),
            _ => markdown_to_plain_text(&markdown),
        };

        let article = if request.save_output {
            Some(
                ArticleStore::new(self.context.paths().clone())
                    .save_generated_article(&title, &format, &output_content)?
                    .summary,
            )
        } else {
            None
        };

        Ok(GenerationOutput {
            title,
            format: format.to_uppercase(),
            content: output_content.clone(),
            preview_html: preview_html(&format, &output_content),
            mode,
            sources,
            article,
        })
    }
}

fn build_title(request: &GenerateArticleRequest) -> String {
    let topic = request.topic.trim();
    if request.platform.trim().is_empty() {
        topic.to_string()
    } else {
        format!("{}|{}", request.platform.trim(), topic)
    }
}

fn compose_markdown(
    title: &str,
    request: &GenerateArticleRequest,
    config: &PostpubConfig,
    mode: &str,
    sources: &[SearchResult],
) -> String {
    let mut lines = Vec::new();
    lines.push(format!("# {title}"));
    lines.push(String::new());
    lines.push(format!(
        "Generated by the Rust postpub pipeline on {}.",
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    lines.push(String::new());
    lines.push(format!(
        "This draft was composed from {} source items using `{mode}` mode.",
        sources.len()
    ));
    if !request.reference_urls.is_empty() {
        lines.push(format!(
            "Reference ratio requested: {:.0}%.",
            request.reference_ratio.max(0.0) * 100.0
        ));
    }
    lines.push(String::new());
    lines.push("## Key Takeaways".to_string());
    lines.push(String::new());
    for source in sources.iter().take(5) {
        lines.push(format!(
            "- {}",
            first_sentence(if !source.abstract_text.is_empty() {
                &source.abstract_text
            } else {
                source.content.as_deref().unwrap_or("")
            })
        ));
    }
    lines.push(String::new());
    lines.push("## Draft".to_string());
    lines.push(String::new());
    lines.push(intro_paragraph(title, mode, sources));
    lines.push(String::new());

    for (index, source) in sources.iter().enumerate() {
        lines.push(format!("### Source {}: {}", index + 1, source.title));
        lines.push(String::new());
        if let Some(date) = &source.published_at {
            lines.push(format!("Published: {date}."));
            lines.push(String::new());
        }
        if !source.abstract_text.is_empty() {
            lines.push(source.abstract_text.clone());
            lines.push(String::new());
        }
        if let Some(content) = &source.content {
            let excerpt = excerpt(content, source.abstract_text.is_empty());
            if !excerpt.is_empty() {
                lines.push(excerpt);
                lines.push(String::new());
            }
        }
        lines.push(format!("Source link: {}", source.url));
        lines.push(String::new());
    }

    lines.push("## Suggested Angle".to_string());
    lines.push(String::new());
    lines.push(format!(
        "Given the configured target length of {}-{} words, the next editing pass can tighten the draft around the strongest two or three source threads and add platform-specific framing where needed.",
        config.min_article_len, config.max_article_len
    ));
    lines.push(String::new());
    lines.push("## Source List".to_string());
    lines.push(String::new());
    for source in sources {
        lines.push(format!("- [{}]({})", source.title, source.url));
    }

    lines.join("\n")
}

fn intro_paragraph(title: &str, mode: &str, sources: &[SearchResult]) -> String {
    let source_titles = sources
        .iter()
        .take(3)
        .map(|item| item.title.as_str())
        .collect::<Vec<_>>();
    if source_titles.is_empty() {
        format!("{title} is ready for a first editing pass.")
    } else {
        format!(
            "{title} is framed around {} and assembled through the Rust `{mode}` retrieval pipeline, which keeps the drafting step grounded in concrete source material instead of opaque prompt-only output.",
            source_titles.join(", ")
        )
    }
}

fn first_sentence(text: &str) -> String {
    let sentence = text
        .split_terminator(['.', '!', '?'])
        .next()
        .unwrap_or(text)
        .trim();
    if sentence.is_empty() {
        "Source content is available for review.".to_string()
    } else {
        format!("{sentence}.")
    }
}

fn excerpt(text: &str, longer: bool) -> String {
    let target_chars = if longer { 520 } else { 260 };
    let mut output = String::new();
    for (index, ch) in text.chars().enumerate() {
        if index >= target_chars {
            output.push_str("...");
            break;
        }
        output.push(ch);
    }
    output
}

fn render_preview_html(
    format: &str,
    markdown: &str,
    title: &str,
    mode: &str,
    sources: &[SearchResult],
    request: &GenerateArticleRequest,
    templates: &TemplateStore,
    config: &PostpubConfig,
) -> Result<String> {
    if format != "html" {
        return Ok(markdown_to_html(markdown));
    }

    let body_html = markdown_to_html(markdown);
    let summary = format!(
        "Mode: {mode}. Sources: {}. Topic: {}.",
        sources.len(),
        request.topic
    );
    let generated_at = Utc::now().format("%Y-%m-%d %H:%M UTC").to_string();
    let selected_template = templates.load_selected_template(
        request
            .template_category
            .as_deref()
            .or(Some(config.template_category.as_str())),
        request
            .template_name
            .as_deref()
            .or(Some(config.template_name.as_str())),
    )?;

    if config.use_template {
        if let Some(template) = selected_template {
            return Ok(apply_template(
                &template.content,
                title,
                &summary,
                &generated_at,
                &body_html,
            ));
        }
    }

    Ok(format!(
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><title>{title}</title><style>body{{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f8fafc;color:#0f172a}}main{{max-width:860px;margin:0 auto;padding:32px 20px 64px}}header{{margin-bottom:24px}}.meta{{color:#64748b}}</style></head><body><main><header><h1>{title}</h1><p class=\"meta\">{summary}</p><p class=\"meta\">Generated at {generated_at}</p></header>{body_html}</main></body></html>"
    ))
}

fn apply_template(
    template: &str,
    title: &str,
    summary: &str,
    generated_at: &str,
    content_html: &str,
) -> String {
    template
        .replace("{{title}}", title)
        .replace("{{summary}}", summary)
        .replace("{{generated_at}}", generated_at)
        .replace("{{content}}", content_html)
}

fn markdown_to_plain_text(markdown: &str) -> String {
    markdown
        .lines()
        .map(|line| {
            line.trim_start_matches('#')
                .trim_start_matches('-')
                .trim()
                .to_string()
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn normalize_format(format: &str) -> String {
    match format.trim().to_ascii_lowercase().as_str() {
        "markdown" | "md" => "md".to_string(),
        "txt" | "text" => "txt".to_string(),
        _ => "html".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use postpub_types::{GenerateArticleRequest, PlatformSource, PostpubConfig, SearchResult};

    use super::compose_markdown;

    #[test]
    fn composes_markdown_from_sources() {
        let markdown = compose_markdown(
            "web|topic",
            &GenerateArticleRequest {
                topic: "topic".to_string(),
                platform: "web".to_string(),
                reference_urls: vec![],
                reference_ratio: 0.0,
                template_category: None,
                template_name: None,
                save_output: false,
            },
            &PostpubConfig {
                platforms: vec![PlatformSource::default()],
                publish_platform: "web".to_string(),
                img_api: postpub_types::ImageApiConfig::default(),
                publish_targets: vec![],
                use_template: true,
                template_category: "general".to_string(),
                template_name: "magazine".to_string(),
                use_compress: false,
                aiforge_search_max_results: 8,
                aiforge_search_min_results: 3,
                min_article_len: 900,
                max_article_len: 1800,
                auto_publish: false,
                article_format: "html".to_string(),
                format_publish: true,
            },
            "search",
            &[SearchResult {
                title: "Example result".to_string(),
                url: "https://example.com".to_string(),
                abstract_text: "This is a useful summary for the generated article.".to_string(),
                published_at: Some("2026-03-28".to_string()),
                content: None,
            }],
        );

        assert!(markdown.contains("# web|topic"));
        assert!(markdown.contains("Example result"));
    }
}
